### ISSUE TITLE
Incorrect documentation for Group and Aggregate

### ISSUE THREAD

**Issue by btruhand** [data-forge/data-forge-ts#5]
Thank you for the library

In the documentation: https://github.com/data-forge/data-forge-ts/blob/master/docs/guide.md#group-and-aggregate I found several issues

First thing is that the example that should be looked at is not #13 but #12. Secondly the code in the example is not actually working with `data-forge v1.0.10`. Running the example gives me the following error

```
$ > node examples/12.\ Group\ and\ aggregate\ sales\ data/index.js
-- Output dataframe:
/Users/btara.truhandarien/Code/data-forge-examples-and-tests/examples/12. Group and aggregate sales data/index.js:47
        Sales: group.select(row => row.Sales).sum(),
                                              ^

TypeError: group.select(...).sum is not a function
    at SelectIterator.salesData.groupBy.select.group [as selector] (/Users/btara.truhandarien/Code/data-forge-examples-and-tests/examples/12. Group and aggregate sales data/index.js:47:47)
    at SelectIterator.next (/Users/btara.truhandarien/Code/data-forge-examples-and-tests/node_modules/data-forge/build/lib/iterators/select-iterator.js:20:25)
    at ColumnNamesIterator.next (/Users/btara.truhandarien/Code/data-forge-examples-and-tests/node_modules/data-forge/build/lib/iterators/column-names-iterator.js:58:50)
    at Function.from (native)
    at DataFrame.getColumnNames (/Users/btara.truhandarien/Code/data-forge-examples-and-tests/node_modules/data-forge/build/lib/dataframe.js:337:22)
    at DataFrame.toString (/Users/btara.truhandarien/Code/data-forge-examples-and-tests/node_modules/data-forge/build/lib/dataframe.js:1917:32)
    at Object.<anonymous> (/Users/btara.truhandarien/Code/data-forge-examples-and-tests/examples/12. Group and aggregate sales data/index.js:53:24)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
``` 

I find that modifying the aggregation to be
```javascript
var summarized = salesData
    .groupBy(row => row.ClientName)
    .select(group => ({
        ClientName: group.first().ClientName,

        // Sum sales per client.
        Sales: group.select(row => row.Sales).deflate().sum(),
    }))
    .inflate() // Series -> DataFrame.
    ;
```
Works as expected

**Comment by ashleydavis** [comment]
Thanks so much for logging an issue. It's been tricky keeping the docs up to date while Data-Forge evolves!

I've modify the docs to your proposed solution. Thanks again!

**Comment by ashleydavis** [comment]
Hey Btara,

Just wondering if you've seen my new library yet?

It's called Data-Forge Plot and integrates plotting/charting with Data-Forge.

Please check out [my blog post on it](http://www.the-data-wrangler.com/introducing-data-forge-plot/).

It's early days yet, but I'm trying to collect feedback on it.

**Comment by btruhand** [comment]
Looks great! Actually I've been using data-forge for analyzing (just simple calculations, aggregations etc.). Wanted to plot the resulting data and for now doing it with excel. This is so useful to have and would go a long way to automate things further

If I have the time I'll check it out and if there are issues or thoughts I'll raise them

I'm assuming right now there's no documentation on the API for it other than the blog?

**Comment by ashleydavis** [comment]
Awesome! Hope to get some feedback from you ;)

Yes sorry no documentation and the API will likely changes.  I've prototype the API, so you can try it out! I wrote the blog post to try and better formulate the idea and get feedback, so the API will change if you find problems or suggest improvements.

I'll get to the docs in a few weeks probably, once I'm settled on the API.

**Comment by ashleydavis** [comment]
If you get a chance, pls jump in and put a star on the new repo:
https://github.com/data-forge/data-forge-plot

**Comment by btruhand** [comment]
Certainly! I've starred it :)
